# # # # # # # #
#   K i k o   #
# # # # # # # #

# - markdown: kramdown

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

title: "Lukas Rosenstock"
tagline: ""
description: "Follow <a href=\"https://micro.blog/lukas\">@lukas on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/lukas\">@lukas on Micro.blog</a>."
baseurl: ""
url: "http://lukasrosenstock.net"
markdown: "kramdown"
username: "lukas"
microblog_user: "lukas"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Lukas Rosenstock"
name: "Lukas Rosenstock"
gravatar_hash: "cabb2e7244a803b976281ae5c2598124"
avatar: "https://micro.blog/lukas/avatar.jpg"
full_name: "Lukas Rosenstock"
bio: ""
twitter_username: ""
github_username: ""
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "Poland"
site_id: "3438"
gems: ["jekyll-paginate"]
itunes_category: "Society & Culture"
itunes_subcategory: "Personal Journals"